# Generated by Django 6.0.7 on 2026-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_galleryimage_image_url_galleryimage_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='updatepost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
