# Generated by Django 6.0.7 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contactmessage_is_read_contactmessage_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
