# Generated by Django 6.0.7 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_galleryimage_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='homepage/videos/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='homepage/posters/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
