# Generated by Django 6.0.7 on 2026-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_homepagemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('profile_photo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('relative_time_description', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
