# Generated by Django 6.0.7 on 2026-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_googlereview_reviewsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, null=True, storage='video_storage', upload_to='gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='homepagemedia',
            name='video',
            field=models.FileField(blank=True, null=True, storage='video_storage', upload_to='homepage/videos/'),
        ),
    ]
