# Generated by Django 6.0.7 on 2026-07-21 16:33

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_galleryimage_video_alter_homepagemedia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, null=True, storage=content.models.get_video_storage, upload_to='gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='homepagemedia',
            name='video',
            field=models.FileField(blank=True, null=True, storage=content.models.get_video_storage, upload_to='homepage/videos/'),
        ),
    ]
